using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
using SqlScripter.Models;

namespace SqlScripter.Services;

/// <summary>
/// Generates "drop &amp; recreate" T-SQL for a selection of database objects.
/// For every object it emits:
///   1. an existence check that DROPs the object if it is already present, then
///   2. a full recreation script (CREATE TABLE with columns / constraints / indexes
///      for tables, or the stored module definition for views / procedures).
/// All metadata is read from the live database via the system catalog views so the
/// output reflects the object's current shape.
/// </summary>
public sealed class SqlScriptGenerator
{
    public async Task<string> GenerateAsync(
        string connectionString,
        IReadOnlyList<DbObjectInfo> objects,
        ScriptOptions options,
        CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* ============================================================");
        sb.AppendLine("   Script generated by SqlScripter");
        sb.AppendLine($"   Objects: {objects.Count}");
        sb.AppendLine("   ============================================================ */");
        sb.AppendLine();
        sb.AppendLine("SET ANSI_NULLS ON;");
        sb.AppendLine("SET QUOTED_IDENTIFIER ON;");
        sb.AppendLine("GO");
        sb.AppendLine();

        await using var conn = new SqlConnection(connectionString);
        await conn.OpenAsync(ct);

        foreach (var obj in objects)
        {
            ct.ThrowIfCancellationRequested();

            sb.AppendLine("/* ------------------------------------------------------------");
            sb.AppendLine($"   {Describe(obj.Type)}: {obj.Display}");
            sb.AppendLine("   ------------------------------------------------------------ */");

            switch (obj.Type)
            {
                case SqlObjectType.Table:
                    await ScriptTableAsync(conn, obj, sb, options, ct);
                    break;
                case SqlObjectType.View:
                    await ScriptModuleAsync(conn, obj, sb, "V", "VIEW", options, ct);
                    break;
                case SqlObjectType.StoredProcedure:
                    await ScriptModuleAsync(conn, obj, sb, "P", "PROCEDURE", options, ct);
                    break;
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string Describe(SqlObjectType t) => t switch
    {
        SqlObjectType.Table => "TABLE",
        SqlObjectType.View => "VIEW",
        SqlObjectType.StoredProcedure => "STORED PROCEDURE",
        _ => t.ToString()
    };

    // ---------------------------------------------------------------------
    // Views & stored procedures: drop, then replay the stored module text.
    // ---------------------------------------------------------------------
    private static async Task ScriptModuleAsync(
        SqlConnection conn, DbObjectInfo obj, StringBuilder sb,
        string typeCode, string keyword, ScriptOptions options, CancellationToken ct)
    {
        if (options.IncludeDropChecks)
            AppendDropIfExists(sb, obj, typeCode, keyword);

        string? definition = await GetModuleDefinitionAsync(conn, obj.FullName, ct);
        if (string.IsNullOrWhiteSpace(definition))
        {
            sb.AppendLine($"/* Definition for {obj.Display} could not be retrieved (it may be encrypted). */");
            return;
        }

        // A CREATE VIEW / CREATE PROCEDURE statement must be the first statement in
        // its batch, so it gets its own batch delimited by GO.
        sb.AppendLine(definition.TrimEnd());
        sb.AppendLine("GO");
    }

    private static async Task<string?> GetModuleDefinitionAsync(SqlConnection conn, string fullName, CancellationToken ct)
    {
        const string sql = """
            SELECT m.definition
            FROM sys.sql_modules m
            WHERE m.object_id = OBJECT_ID(@name);
            """;
        await using var cmd = new SqlCommand(sql, conn);
        cmd.Parameters.AddWithValue("@name", fullName);
        var result = await cmd.ExecuteScalarAsync(ct);
        return result as string;
    }

    // ---------------------------------------------------------------------
    // Tables: rebuild the full CREATE TABLE plus constraints and indexes.
    // ---------------------------------------------------------------------
    private static async Task ScriptTableAsync(SqlConnection conn, DbObjectInfo obj, StringBuilder sb, ScriptOptions options, CancellationToken ct)
    {
        if (options.IncludeDropChecks)
            AppendDropIfExists(sb, obj, "U", "TABLE");

        var columns = await GetColumnsAsync(conn, obj.FullName, ct);
        if (columns.Count == 0)
        {
            sb.AppendLine($"/* Table {obj.Display} has no readable columns. */");
            return;
        }

        // CREATE TABLE with the column list (defaults are emitted inline).
        sb.AppendLine($"CREATE TABLE {obj.FullName} (");
        for (int i = 0; i < columns.Count; i++)
        {
            var comma = i < columns.Count - 1 ? "," : string.Empty;
            sb.AppendLine($"    {columns[i].ToColumnDefinition()}{comma}");
        }
        sb.AppendLine(");");
        sb.AppendLine("GO");

        // Primary key & unique constraints.
        foreach (var c in await GetKeyConstraintsAsync(conn, obj, ct))
        {
            sb.AppendLine(c);
            sb.AppendLine("GO");
        }

        // Foreign keys.
        foreach (var fk in await GetForeignKeysAsync(conn, obj, ct))
        {
            sb.AppendLine(fk);
            sb.AppendLine("GO");
        }

        // Check constraints.
        foreach (var chk in await GetCheckConstraintsAsync(conn, obj, ct))
        {
            sb.AppendLine(chk);
            sb.AppendLine("GO");
        }

        // Secondary (non-constraint) indexes.
        foreach (var ix in await GetIndexesAsync(conn, obj, ct))
        {
            sb.AppendLine(ix);
            sb.AppendLine("GO");
        }

        // Optionally reproduce the table's current row data as INSERT statements.
        if (options.IncludeTableData)
            await ScriptTableDataAsync(conn, obj, columns, sb, options.MaxDataRows, ct);
    }

    private static async Task ScriptTableDataAsync(
        SqlConnection conn, DbObjectInfo obj, List<ColumnInfo> columns, StringBuilder sb, int maxRows, CancellationToken ct)
    {
        // Computed columns and rowversion/timestamp columns cannot be inserted into.
        var insertable = columns
            .Where(c => !c.IsComputed &&
                        !c.TypeName.Equals("timestamp", StringComparison.OrdinalIgnoreCase) &&
                        !c.TypeName.Equals("rowversion", StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (insertable.Count == 0)
            return;

        var hasIdentity = insertable.Any(c => c.IsIdentity);
        var columnList = string.Join(", ", insertable.Select(c => $"[{c.Name}]"));

        var rows = new StringBuilder();
        var rowCount = 0;

        var top = maxRows > 0 ? $"TOP ({maxRows}) " : string.Empty;
        var select = $"SELECT {top}{columnList} FROM {obj.FullName};";
        await using (var cmd = new SqlCommand(select, conn))
        await using (var r = await cmd.ExecuteReaderAsync(ct))
        {
            while (await r.ReadAsync(ct))
            {
                var values = new string[insertable.Count];
                for (var i = 0; i < insertable.Count; i++)
                    values[i] = FormatSqlLiteral(r.GetValue(i));

                rows.AppendLine($"INSERT INTO {obj.FullName} ({columnList}) VALUES ({string.Join(", ", values)});");
                rowCount++;
            }
        }

        if (rowCount == 0)
        {
            sb.AppendLine($"/* {obj.Display} contains no data rows. */");
            sb.AppendLine();
            return;
        }

        sb.AppendLine($"/* Data: {rowCount} row(s) from {obj.Display} */");
        if (maxRows > 0 && rowCount == maxRows)
            sb.AppendLine($"/* NOTE: limited to the first {maxRows} row(s); the table may contain more. */");
        // SET IDENTITY_INSERT and the INSERTs are kept in one batch (no GO between)
        // so the identity override stays in effect for every row.
        if (hasIdentity)
            sb.AppendLine($"SET IDENTITY_INSERT {obj.FullName} ON;");
        sb.Append(rows);
        if (hasIdentity)
            sb.AppendLine($"SET IDENTITY_INSERT {obj.FullName} OFF;");
        sb.AppendLine("GO");
    }

    /// <summary>Formats a CLR value read from the database as a T-SQL literal.</summary>
    private static string FormatSqlLiteral(object? value)
    {
        if (value is null || value is DBNull)
            return "NULL";

        switch (value)
        {
            case bool b:
                return b ? "1" : "0";
            case byte[] bytes:
                return "0x" + Convert.ToHexString(bytes);
            case Guid g:
                return $"'{g}'";
            case DateTime dt:
                return $"'{dt.ToString("yyyy-MM-ddTHH:mm:ss.fffffff", CultureInfo.InvariantCulture)}'";
            case DateTimeOffset dto:
                return $"'{dto.ToString("yyyy-MM-ddTHH:mm:ss.fffffffzzz", CultureInfo.InvariantCulture)}'";
            case TimeSpan ts:
                return $"'{ts.ToString("c", CultureInfo.InvariantCulture)}'";
            case float f:
                return f.ToString("R", CultureInfo.InvariantCulture);
            case double d:
                return d.ToString("R", CultureInfo.InvariantCulture);
            case decimal m:
                return m.ToString(CultureInfo.InvariantCulture);
            case byte or sbyte or short or ushort or int or uint or long or ulong:
                return Convert.ToString(value, CultureInfo.InvariantCulture)!;
            case string s:
                return $"N'{s.Replace("'", "''")}'";
            default:
                return $"N'{value.ToString()?.Replace("'", "''")}'";
        }
    }

    private sealed class ColumnInfo
    {
        public required string Name { get; init; }
        public required string TypeName { get; init; }
        public required string TypeSchema { get; init; }
        public bool IsUserDefined { get; init; }
        public int MaxLength { get; init; }
        public int Precision { get; init; }
        public int Scale { get; init; }
        public bool IsNullable { get; init; }
        public bool IsIdentity { get; init; }
        public long IdentitySeed { get; init; }
        public long IdentityIncrement { get; init; }
        public bool IsComputed { get; init; }
        public string? ComputedDefinition { get; init; }
        public bool IsPersisted { get; init; }
        public string? DefaultName { get; init; }
        public string? DefaultDefinition { get; init; }
        public string? Collation { get; init; }
        public string? DatabaseCollation { get; init; }

        public string ToColumnDefinition()
        {
            if (IsComputed)
            {
                var computed = $"[{Name}] AS {ComputedDefinition}";
                if (IsPersisted)
                    computed += " PERSISTED";
                return computed;
            }

            var sb = new StringBuilder();
            sb.Append($"[{Name}] {FormatType()}");

            // Only emit COLLATE when it differs from the database default to keep output tidy.
            if (!string.IsNullOrEmpty(Collation) &&
                !string.Equals(Collation, DatabaseCollation, StringComparison.OrdinalIgnoreCase))
            {
                sb.Append($" COLLATE {Collation}");
            }

            if (IsIdentity)
                sb.Append($" IDENTITY({IdentitySeed},{IdentityIncrement})");

            sb.Append(IsNullable ? " NULL" : " NOT NULL");

            if (!string.IsNullOrEmpty(DefaultDefinition))
            {
                if (!string.IsNullOrEmpty(DefaultName))
                    sb.Append($" CONSTRAINT [{DefaultName}]");
                sb.Append($" DEFAULT {DefaultDefinition}");
            }

            return sb.ToString();
        }

        private string FormatType()
        {
            if (IsUserDefined)
                return $"[{TypeSchema}].[{TypeName}]";

            var t = TypeName.ToLowerInvariant();
            var baseName = $"[{TypeName}]";

            switch (t)
            {
                case "char":
                case "varchar":
                case "binary":
                case "varbinary":
                    return $"{baseName}({(MaxLength == -1 ? "MAX" : MaxLength.ToString(CultureInfo.InvariantCulture))})";
                case "nchar":
                case "nvarchar":
                    // max_length is stored in bytes for unicode types.
                    return $"{baseName}({(MaxLength == -1 ? "MAX" : (MaxLength / 2).ToString(CultureInfo.InvariantCulture))})";
                case "decimal":
                case "numeric":
                    return $"{baseName}({Precision},{Scale})";
                case "datetime2":
                case "datetimeoffset":
                case "time":
                    return $"{baseName}({Scale})";
                case "float":
                    return Precision == 53 ? baseName : $"{baseName}({Precision})";
                default:
                    return baseName;
            }
        }
    }

    private static async Task<List<ColumnInfo>> GetColumnsAsync(SqlConnection conn, string fullName, CancellationToken ct)
    {
        const string sql = """
            SELECT
                c.name                                   AS ColumnName,
                t.name                                   AS TypeName,
                SCHEMA_NAME(t.schema_id)                 AS TypeSchema,
                t.is_user_defined                        AS IsUserDefined,
                c.max_length                             AS MaxLength,
                c.precision                              AS Precision,
                c.scale                                  AS Scale,
                c.is_nullable                            AS IsNullable,
                c.is_identity                            AS IsIdentity,
                ic.seed_value                            AS SeedValue,
                ic.increment_value                       AS IncrementValue,
                c.is_computed                            AS IsComputed,
                cc.definition                            AS ComputedDefinition,
                cc.is_persisted                          AS IsPersisted,
                dc.name                                  AS DefaultName,
                dc.definition                            AS DefaultDefinition,
                c.collation_name                         AS CollationName,
                CONVERT(nvarchar(128), DATABASEPROPERTYEX(DB_NAME(), 'Collation')) AS DbCollation
            FROM sys.columns c
            INNER JOIN sys.types t            ON t.user_type_id = c.user_type_id
            LEFT JOIN sys.identity_columns ic ON ic.object_id = c.object_id AND ic.column_id = c.column_id
            LEFT JOIN sys.computed_columns cc ON cc.object_id = c.object_id AND cc.column_id = c.column_id
            LEFT JOIN sys.default_constraints dc ON dc.object_id = c.default_object_id
            WHERE c.object_id = OBJECT_ID(@name)
            ORDER BY c.column_id;
            """;

        var list = new List<ColumnInfo>();
        await using var cmd = new SqlCommand(sql, conn);
        cmd.Parameters.AddWithValue("@name", fullName);
        await using var r = await cmd.ExecuteReaderAsync(ct);

        while (await r.ReadAsync(ct))
        {
            list.Add(new ColumnInfo
            {
                Name = r.GetString(r.GetOrdinal("ColumnName")),
                TypeName = r.GetString(r.GetOrdinal("TypeName")),
                TypeSchema = GetStringOr(r, "TypeSchema", "dbo"),
                IsUserDefined = r.GetBoolean(r.GetOrdinal("IsUserDefined")),
                MaxLength = Convert.ToInt32(r["MaxLength"], CultureInfo.InvariantCulture),
                Precision = Convert.ToInt32(r["Precision"], CultureInfo.InvariantCulture),
                Scale = Convert.ToInt32(r["Scale"], CultureInfo.InvariantCulture),
                IsNullable = r.GetBoolean(r.GetOrdinal("IsNullable")),
                IsIdentity = r.GetBoolean(r.GetOrdinal("IsIdentity")),
                IdentitySeed = ToInt64(r["SeedValue"]),
                IdentityIncrement = ToInt64(r["IncrementValue"], 1),
                IsComputed = r.GetBoolean(r.GetOrdinal("IsComputed")),
                ComputedDefinition = r["ComputedDefinition"] as string,
                IsPersisted = !r.IsDBNull(r.GetOrdinal("IsPersisted")) && r.GetBoolean(r.GetOrdinal("IsPersisted")),
                DefaultName = r["DefaultName"] as string,
                DefaultDefinition = r["DefaultDefinition"] as string,
                Collation = r["CollationName"] as string,
                DatabaseCollation = r["DbCollation"] as string
            });
        }

        return list;
    }

    private static async Task<List<string>> GetKeyConstraintsAsync(SqlConnection conn, DbObjectInfo obj, CancellationToken ct)
    {
        const string sql = """
            SELECT kc.name AS ConstraintName, kc.type AS KType, i.type_desc AS IndexType,
                   c.name AS ColumnName, ic.is_descending_key AS IsDesc, ic.key_ordinal AS Ordinal
            FROM sys.key_constraints kc
            INNER JOIN sys.indexes i        ON i.object_id = kc.parent_object_id AND i.index_id = kc.unique_index_id
            INNER JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
            INNER JOIN sys.columns c        ON c.object_id = ic.object_id AND c.column_id = ic.column_id
            WHERE kc.parent_object_id = OBJECT_ID(@name)
            ORDER BY kc.name, ic.key_ordinal;
            """;

        // name -> (type, indexType, ordered column list)
        var map = new Dictionary<string, (string KType, string IndexType, List<string> Cols)>();
        var order = new List<string>();

        await using var cmd = new SqlCommand(sql, conn);
        cmd.Parameters.AddWithValue("@name", obj.FullName);
        await using var r = await cmd.ExecuteReaderAsync(ct);
        while (await r.ReadAsync(ct))
        {
            var cname = r.GetString(0);
            if (!map.TryGetValue(cname, out var entry))
            {
                entry = (r.GetString(1).Trim(), r.GetString(2), new List<string>());
                map[cname] = entry;
                order.Add(cname);
            }
            var col = r.GetString(3);
            var desc = r.GetBoolean(4) ? "DESC" : "ASC";
            entry.Cols.Add($"[{col}] {desc}");
        }

        var output = new List<string>();
        foreach (var name in order)
        {
            var (ktype, indexType, cols) = map[name];
            var kind = ktype == "PK" ? "PRIMARY KEY" : "UNIQUE";
            var clustered = indexType.Contains("CLUSTERED", StringComparison.OrdinalIgnoreCase) &&
                            !indexType.Contains("NONCLUSTERED", StringComparison.OrdinalIgnoreCase)
                ? "CLUSTERED" : "NONCLUSTERED";
            output.Add($"ALTER TABLE {obj.FullName} ADD CONSTRAINT [{name}] {kind} {clustered} ({string.Join(", ", cols)});");
        }
        return output;
    }

    private static async Task<List<string>> GetForeignKeysAsync(SqlConnection conn, DbObjectInfo obj, CancellationToken ct)
    {
        const string sql = """
            SELECT fk.name AS FkName,
                   cpar.name AS ParentColumn,
                   SCHEMA_NAME(reft.schema_id) AS RefSchema,
                   reft.name AS RefTable,
                   cref.name AS RefColumn,
                   fk.delete_referential_action_desc AS OnDelete,
                   fk.update_referential_action_desc AS OnUpdate
            FROM sys.foreign_keys fk
            INNER JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
            INNER JOIN sys.columns cpar ON cpar.object_id = fkc.parent_object_id AND cpar.column_id = fkc.parent_column_id
            INNER JOIN sys.tables reft  ON reft.object_id = fk.referenced_object_id
            INNER JOIN sys.columns cref ON cref.object_id = fkc.referenced_object_id AND cref.column_id = fkc.referenced_column_id
            WHERE fk.parent_object_id = OBJECT_ID(@name)
            ORDER BY fk.name, fkc.constraint_column_id;
            """;

        var map = new Dictionary<string, (string RefSchema, string RefTable, string OnDelete, string OnUpdate, List<string> ParentCols, List<string> RefCols)>();
        var order = new List<string>();

        await using var cmd = new SqlCommand(sql, conn);
        cmd.Parameters.AddWithValue("@name", obj.FullName);
        await using var r = await cmd.ExecuteReaderAsync(ct);
        while (await r.ReadAsync(ct))
        {
            var fkName = r.GetString(0);
            if (!map.TryGetValue(fkName, out var entry))
            {
                entry = (r.GetString(2), r.GetString(3), r.GetString(5).Replace('_', ' '), r.GetString(6).Replace('_', ' '), new List<string>(), new List<string>());
                map[fkName] = entry;
                order.Add(fkName);
            }
            entry.ParentCols.Add($"[{r.GetString(1)}]");
            entry.RefCols.Add($"[{r.GetString(4)}]");
        }

        var output = new List<string>();
        foreach (var name in order)
        {
            var e = map[name];
            var sb = new StringBuilder();
            sb.Append($"ALTER TABLE {obj.FullName} WITH CHECK ADD CONSTRAINT [{name}] FOREIGN KEY ({string.Join(", ", e.ParentCols)}) ");
            sb.Append($"REFERENCES [{e.RefSchema}].[{e.RefTable}] ({string.Join(", ", e.RefCols)})");
            if (!e.OnDelete.Equals("NO ACTION", StringComparison.OrdinalIgnoreCase))
                sb.Append($" ON DELETE {e.OnDelete}");
            if (!e.OnUpdate.Equals("NO ACTION", StringComparison.OrdinalIgnoreCase))
                sb.Append($" ON UPDATE {e.OnUpdate}");
            sb.Append(';');
            output.Add(sb.ToString());
        }
        return output;
    }

    private static async Task<List<string>> GetCheckConstraintsAsync(SqlConnection conn, DbObjectInfo obj, CancellationToken ct)
    {
        const string sql = """
            SELECT cc.name AS ConstraintName, cc.definition AS Definition
            FROM sys.check_constraints cc
            WHERE cc.parent_object_id = OBJECT_ID(@name)
            ORDER BY cc.name;
            """;

        var output = new List<string>();
        await using var cmd = new SqlCommand(sql, conn);
        cmd.Parameters.AddWithValue("@name", obj.FullName);
        await using var r = await cmd.ExecuteReaderAsync(ct);
        while (await r.ReadAsync(ct))
        {
            var name = r.GetString(0);
            var def = r.GetString(1);
            output.Add($"ALTER TABLE {obj.FullName} WITH CHECK ADD CONSTRAINT [{name}] CHECK {def};");
        }
        return output;
    }

    private static async Task<List<string>> GetIndexesAsync(SqlConnection conn, DbObjectInfo obj, CancellationToken ct)
    {
        const string sql = """
            SELECT i.name AS IndexName, i.type_desc AS IndexType, i.is_unique AS IsUnique,
                   i.filter_definition AS FilterDefinition,
                   c.name AS ColumnName, ic.is_descending_key AS IsDesc,
                   ic.is_included_column AS IsIncluded, ic.key_ordinal AS KeyOrdinal,
                   ic.index_column_id AS IndexColumnId
            FROM sys.indexes i
            INNER JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
            INNER JOIN sys.columns c        ON c.object_id = ic.object_id AND c.column_id = ic.column_id
            WHERE i.object_id = OBJECT_ID(@name)
              AND i.is_primary_key = 0
              AND i.is_unique_constraint = 0
              AND i.type IN (1, 2)            -- clustered / nonclustered rowstore only
              AND i.is_hypothetical = 0
            ORDER BY i.name, ic.is_included_column, ic.key_ordinal, ic.index_column_id;
            """;

        var map = new Dictionary<string, (string IndexType, bool IsUnique, string? Filter, List<string> Keys, List<string> Included)>();
        var order = new List<string>();

        await using var cmd = new SqlCommand(sql, conn);
        cmd.Parameters.AddWithValue("@name", obj.FullName);
        await using var r = await cmd.ExecuteReaderAsync(ct);
        while (await r.ReadAsync(ct))
        {
            var name = r.GetString(0);
            if (!map.TryGetValue(name, out var entry))
            {
                entry = (r.GetString(1), r.GetBoolean(2), r["FilterDefinition"] as string, new List<string>(), new List<string>());
                map[name] = entry;
                order.Add(name);
            }
            var col = r.GetString(4);
            var included = r.GetBoolean(6);
            if (included)
                entry.Included.Add($"[{col}]");
            else
                entry.Keys.Add($"[{col}] {(r.GetBoolean(5) ? "DESC" : "ASC")}");
        }

        var output = new List<string>();
        foreach (var name in order)
        {
            var e = map[name];
            var unique = e.IsUnique ? "UNIQUE " : string.Empty;
            var type = e.IndexType.Contains("NONCLUSTERED", StringComparison.OrdinalIgnoreCase) ? "NONCLUSTERED" : "CLUSTERED";
            var sb = new StringBuilder();
            sb.Append($"CREATE {unique}{type} INDEX [{name}] ON {obj.FullName} ({string.Join(", ", e.Keys)})");
            if (e.Included.Count > 0)
                sb.Append($" INCLUDE ({string.Join(", ", e.Included)})");
            if (!string.IsNullOrEmpty(e.Filter))
                sb.Append($" WHERE {e.Filter}");
            sb.Append(';');
            output.Add(sb.ToString());
        }
        return output;
    }

    // ---------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------
    private static void AppendDropIfExists(StringBuilder sb, DbObjectInfo obj, string typeCode, string keyword)
    {
        sb.AppendLine($"IF OBJECT_ID(N'{obj.FullName}', N'{typeCode}') IS NOT NULL");
        sb.AppendLine($"    DROP {keyword} {obj.FullName};");
        sb.AppendLine("GO");
    }

    private static long ToInt64(object? value, long fallback = 0)
        => value is null || value is DBNull ? fallback : Convert.ToInt64(value, CultureInfo.InvariantCulture);

    private static string GetStringOr(SqlDataReader r, string column, string fallback)
    {
        var ordinal = r.GetOrdinal(column);
        return r.IsDBNull(ordinal) ? fallback : r.GetString(ordinal);
    }
}
